# Qt's QML installer preserves file symlinks. Homebrew's relative Cellar links
# must be materialized before macdeployqt can inspect and relocate the binaries.
function(resolve_qml_links bundle_dir source_qml_dir)
    get_filename_component(bundle_dir "${bundle_dir}" ABSOLUTE)
    if(NOT IS_DIRECTORY "${bundle_dir}/Contents/Resources/qml")
        message(FATAL_ERROR "QML deployment directory is missing in ${bundle_dir}")
    endif()
    file(GLOB plugins LIST_DIRECTORIES false "${bundle_dir}/Contents/PlugIns/*.dylib")
    foreach(plugin IN LISTS plugins)
        if(NOT IS_SYMLINK "${plugin}")
            continue()
        endif()
        if(EXISTS "${plugin}")
            file(REAL_PATH "${plugin}" source)
        else()
            get_filename_component(name "${plugin}" NAME)
            file(GLOB_RECURSE candidates FOLLOW_SYMLINKS LIST_DIRECTORIES false "${source_qml_dir}/${name}")
            set(resolved_candidates)
            foreach(candidate IN LISTS candidates)
                file(REAL_PATH "${candidate}" resolved)
                list(APPEND resolved_candidates "${resolved}")
            endforeach()
            list(REMOVE_DUPLICATES resolved_candidates)
            list(LENGTH resolved_candidates count)
            if(NOT count EQUAL 1)
                message(FATAL_ERROR "Cannot resolve deployed QML plugin ${name}")
            endif()
            list(GET resolved_candidates 0 source)
        endif()
        file(REMOVE "${plugin}")
        file(COPY_FILE "${source}" "${plugin}")
    endforeach()

    set(qml_dir "${bundle_dir}/Contents/Resources/qml")
    file(GLOB_RECURSE qml_files LIST_DIRECTORIES false "${qml_dir}/*")
    foreach(qml_file IN LISTS qml_files)
        if(NOT IS_SYMLINK "${qml_file}")
            continue()
        endif()
        if(EXISTS "${qml_file}")
            file(REAL_PATH "${qml_file}" resolved)
            string(FIND "${resolved}" "${bundle_dir}/" in_bundle)
            if(in_bundle EQUAL 0)
                continue()
            endif()
        endif()
        file(RELATIVE_PATH relative "${qml_dir}" "${qml_file}")
        set(source "${source_qml_dir}/${relative}")
        if(NOT EXISTS "${source}" OR IS_DIRECTORY "${source}")
            message(FATAL_ERROR "Cannot resolve deployed QML resource ${relative}")
        endif()
        file(REAL_PATH "${source}" source)
        file(REMOVE "${qml_file}")
        file(COPY_FILE "${source}" "${qml_file}")
    endforeach()
endfunction()
